# Generated by Django 4.2.4 on 2023-09-08 13:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub_main', '0007_category_description_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dyzoccovz/image/upload/v1694180826/cfdiszurokmzpvjxb5r9.png', max_length=255),
        ),
    ]
