# Generated by Django 4.2.4 on 2023-09-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_main', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='github_repo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='live_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
